"""factor tables

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-07 15:55:16.470656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factor_set',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_label', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='factorsetstatus'), nullable=False),
    sa.Column('is_mock', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('published_by', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_label')
    )
    op.create_table('constant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('factor_set_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('value', sa.DECIMAL(precision=20, scale=10), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['factor_set_id'], ['factor_set.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factor_set_id', 'code', name='uq_constant_code')
    )
    op.create_table('equivalence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('factor_set_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source_metric_id', sa.Integer(), nullable=False),
    sa.Column('value_per_unit', sa.DECIMAL(precision=20, scale=10), nullable=False),
    sa.Column('label_template', sa.String(length=255), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['factor_set_id'], ['factor_set.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_metric_id'], ['metric.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factor_set_id', 'code', name='uq_equivalence_code')
    )
    # Contract §2.2 specifies BIGINT for these two primary keys, not INT:
    # ~270 upstream and ~600 downstream rows land per factor set, every
    # version. Autogenerate emitted sa.Integer() because the models declared a
    # bare primary key; both now use db.base.BIGINT_PK.
    op.create_table('factor_upstream',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('factor_set_id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('food_category_id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('value_per_kg', sa.DECIMAL(precision=20, scale=10), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('data_quality', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['factor_set_id'], ['factor_set.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['food_category_id'], ['food_category.id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['metric.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factor_set_id', 'sector_id', 'food_category_id', 'metric_id', name='uq_factor_upstream')
    )
    op.create_table('formula',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('factor_set_id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['factor_set_id'], ['factor_set.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metric_id'], ['metric.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factor_set_id', 'metric_id', name='uq_formula_metric')
    )
    # Contract §2.2 specifies BIGINT for these two primary keys, not INT:
    # ~270 upstream and ~600 downstream rows land per factor set, every
    # version. Autogenerate emitted sa.Integer() because the models declared a
    # bare primary key; both now use db.base.BIGINT_PK.
    op.create_table('factor_downstream',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('factor_set_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('food_category_id', sa.Integer(), nullable=True),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('value_per_kg', sa.DECIMAL(precision=20, scale=10), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('data_quality', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ),
    sa.ForeignKeyConstraint(['factor_set_id'], ['factor_set.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['food_category_id'], ['food_category.id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['metric.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factor_set_id', 'destination_id', 'food_category_id', 'metric_id', name='uq_factor_downstream')
    )
    # ### end Alembic commands ###

    # Contract §2.2: MySQL treats NULLs as distinct, so the UniqueConstraint
    # just created on factor_downstream does not stop a second
    # `food_category_id IS NULL` row for the same (factor_set, destination,
    # metric) — exactly the "applies to every category" rows the constraint
    # most needs to guard. This functional index collapses NULL to 0 via
    # COALESCE before comparing, so a second generic row collides for real.
    # Not autogenerated: autogenerate cannot emit a functional index on its
    # own, and declaring it as a SQLAlchemy Index on the model instead makes
    # tests/test_migrations.py's compare_metadata misreport it as a changed
    # index every run (MySQL/SQLAlchemy can only reflect an expression index
    # back out as an "approximate signature") — see the docstring on
    # admin.factor_models.FactorDownstream.
    op.execute(
        "CREATE UNIQUE INDEX uq_factor_downstream_generic "
        "ON factor_downstream "
        "(factor_set_id, destination_id, (COALESCE(food_category_id, 0)), metric_id)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX uq_factor_downstream_generic ON factor_downstream")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('factor_downstream')
    op.drop_table('formula')
    op.drop_table('factor_upstream')
    op.drop_table('equivalence')
    op.drop_table('constant')
    op.drop_table('factor_set')
    # ### end Alembic commands ###
