"""comparison scenarios

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-08 08:09:30.030870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comparison_scenario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('food_category_id', sa.Integer(), nullable=True),
    sa.Column('gwp_horizon', sa.SmallInteger(), server_default='100', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['food_category_id'], ['food_category.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.CheckConstraint('gwp_horizon IN (20, 100)', name='ck_comparison_scenario_gwp_horizon')
    )
    op.create_table('comparison_scenario_line',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('qty_kg', sa.DECIMAL(precision=16, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['comparison_scenario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'destination_id', name='uq_comparison_scenario_line')
    )
    # ### end Alembic commands ###
    #
    # Autogenerate also proposed dropping and recreating
    # 'uq_factor_downstream_generic' on factor_downstream with a plain
    # 'food_category_id' column in place of the functional
    # '(COALESCE(food_category_id, 0))' key part. That is a false positive,
    # not a real change: alembic/versions/0005_factors.py's own docstring and
    # tests/test_migrations.py's `_include_object` explain why - SQLAlchemy's
    # MySQL dialect cannot reflect a functional index's expression key part
    # back out correctly, so autogenerate compares its own mis-reflection of
    # the index against the model and reports a difference that does not
    # exist in the database. Reapplying that pair of ops here would replace
    # the real functional index 0005 created with a broken plain-column one,
    # silently reintroducing the duplicate-generic-row bug 0005 exists to
    # close. Left out of this migration entirely; the index 0005 created is
    # untouched.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comparison_scenario_line')
    op.drop_table('comparison_scenario')
    # ### end Alembic commands ###
