"""ip block

Revision ID: 0007
Revises: 0006
Create Date: 2026-08-08 21:19:38.121614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, Sequence[str], None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_block',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip_hmac', sa.CHAR(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_hmac')
    )
    # ### end Alembic commands ###
    #
    # Autogenerate also proposed dropping and recreating
    # 'uq_factor_downstream_generic' on factor_downstream with a plain
    # 'food_category_id' column in place of the functional
    # '(COALESCE(food_category_id, 0))' key part. That is the same false
    # positive documented in alembic/versions/0006_comparison_scenarios.py and
    # tests/test_migrations.py's `_include_object`: SQLAlchemy's MySQL dialect
    # cannot reflect a functional index's expression key part back out
    # correctly, so autogenerate compares its own mis-reflection against the
    # model and reports a difference that does not exist in the database.
    # Reapplying that pair of ops here would replace the real functional
    # index 0005 created with a broken plain-column one, silently
    # reintroducing the duplicate-generic-row bug 0005 exists to close. Left
    # out of this migration entirely; the index 0005 created is untouched.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ip_block')
    # ### end Alembic commands ###
