"""submissions

Revision ID: 0008
Revises: 0007
Create Date: 2026-08-09 15:14:59.630412

The three tables of contract §2.3 — `submission`, `submission_entry`,
`submission_line` — filed together, because one `POST /api/v1/calculate`
writes all three (§5.3).

**This is 0008, on top of 0007.** `docs/ToB_v3.0.md` §1.3 tells B to file it
as `0006` with `down_revision = "0005"`. That was true when it was written;
`0006` (comparison scenarios) and `0007` (`ip_block`) have both landed since,
and contract §8.3 change 10 and §2.3 both correct it explicitly. Following
ToB literally would produce a third head — not a merge conflict but an
ambiguous chain, with `upgrade heads` failing partway through on a table that
already exists. MySQL DDL autocommits, so the recovery is `DROP DATABASE`.

**The multi-entry shape is filed directly, with no flat intermediate.** The
v0.1 single-entry shape put `sector_id` and `food_category_id` on
`submission` and keyed `submission_line` on `submission_id`. These are the
same three tables the multi-entry shape needs, so filing the flat one first
would mean two migrations and one of them wasted.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, Sequence[str], None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('token', sa.CHAR(length=36), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('factor_set_id', sa.Integer(), nullable=False),
    sa.Column('gwp_horizon', sa.SmallInteger(), server_default='100', nullable=False),
    sa.Column('excluded_from_public', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('exclusion_reason', sa.String(length=255), nullable=True),
    sa.CheckConstraint('gwp_horizon IN (20, 100)', name='ck_submission_horizon'),
    sa.ForeignKeyConstraint(['factor_set_id'], ['factor_set.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('submission_entry',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('food_category_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['food_category_id'], ['food_category.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'sector_id', 'food_category_id', name='uq_submission_entry')
    )
    op.create_table('submission_line',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('submission_entry_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('scenario', sa.Enum('current', 'alternative', name='scenario'), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('qty_kg', sa.DECIMAL(precision=16, scale=3), nullable=False),
    sa.CheckConstraint('qty_kg >= 0', name='ck_submission_line_qty'),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ),
    sa.ForeignKeyConstraint(['submission_entry_id'], ['submission_entry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_entry_id', 'scenario', 'destination_id', name='uq_submission_line_scope')
    )
    # ### end Alembic commands ###

    # Contract §2.3, and the same defect B found in `factor_downstream` that
    # §2.2 credits to her by name: MySQL treats NULLs as distinct inside a
    # UNIQUE key, so the UniqueConstraint just created on submission_entry does
    # NOT stop a second `food_category_id IS NULL` row for the same
    # (submission, sector) — exactly the "the user did not break waste down by
    # type" rows it most needs to guard. Two such entries then hold one user's
    # single answer twice, `POST /calculate` writes them both without error,
    # and §5.4's by_sector aggregation counts it twice. Nothing in the logs.
    # COALESCE collapses NULL to 0 before comparing, so the second one
    # collides for real; an AUTO_INCREMENT food_category.id is never 0, so a
    # specific row and a generic row still coexist as the lookup order
    # requires.
    #
    # Written as raw SQL rather than op.create_index, matching
    # alembic/versions/0005_factors.py. Autogenerate *detected* this index as
    # a plain ('submission_id', 'sector_id') pair — it dropped the expression
    # key part on the way in — and only kept the COALESCE because it rendered
    # the model's own text() back out. That round trip is not something to
    # rely on for the one constraint in this migration that fails silently.
    op.execute(
        "CREATE UNIQUE INDEX uq_submission_entry_generic "
        "ON submission_entry "
        "(submission_id, sector_id, (COALESCE(food_category_id, 0)))"
    )

    # Autogenerate also proposed dropping and recreating
    # 'uq_factor_downstream_generic' on factor_downstream. That is the same
    # false positive documented in 0006 and 0007 and in tests/test_migrations.py's
    # `_include_object`: SQLAlchemy's MySQL dialect cannot reflect a functional
    # index's expression key part back out correctly, so autogenerate compares
    # its own mis-reflection against the model and reports a difference that
    # does not exist in the database. Reapplying that pair of ops here would
    # replace the real functional index 0005 created with a broken
    # plain-column one, silently reintroducing the duplicate-generic-row bug
    # 0005 exists to close. Left out entirely; the index 0005 created is
    # untouched.


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX uq_submission_entry_generic ON submission_entry")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission_line')
    op.drop_table('submission_entry')
    op.drop_table('submission')
    # ### end Alembic commands ###
